#ifndef VINOX_VINOX_H
#define VINOX_VINOX_H

#include <stddef.h>
#include <stdint.h>

#include "vinox/export.h"

#ifdef __cplusplus
extern "C" {
#endif

#define VINOX_ABI_VERSION 1u

typedef enum vinox_status {
    VINOX_STATUS_OK = 0,
    VINOX_STATUS_INVALID_ARGUMENT = 1,
    VINOX_STATUS_INCOMPATIBLE_ABI = 2,
    VINOX_STATUS_RUNTIME_ERROR = 3,
    VINOX_STATUS_CANCELLED = 4
} vinox_status;

typedef struct vinox_version_info {
    uint32_t struct_size;
    uint32_t abi_version;
    uint32_t major;
    uint32_t minor;
    uint32_t patch;
    const char* version_string;
} vinox_version_info;

VINOX_API vinox_status vinox_get_version(vinox_version_info* version_info);

/**
 * @brief Categorizes the provenance and origin of content crossing VINOX boundaries.
 */
typedef enum vinox_provenance_kind {
    VINOX_PROVENANCE_SOURCE_LITERAL   = 0,  /* Untransformed literal input / source string */
    VINOX_PROVENANCE_TOOL_EVIDENCE   = 1,  /* Verified evidence produced by an external tool/MCP */
    VINOX_PROVENANCE_MODEL_GENERATED = 2,  /* Text output generated by an LLM backend */
    VINOX_PROVENANCE_DERIVED_CONTEXT = 3   /* Reconstructed, summarized or transformed context */
} vinox_provenance_kind;

/**
 * @brief Metadata envelope for transporting provenance across VINOX module boundaries.
 */
typedef struct vinox_provenance_meta {
    uint32_t struct_size;
    uint32_t kind;             /* vinox_provenance_kind */
    const char* source_id;     /* Optional source identifier (e.g. URI, hash, tool name) */
    uint64_t timestamp_ms;     /* Timestamp in UTC milliseconds */
} vinox_provenance_meta;

#define VINOX_PROVENANCE_META_MIN_SIZE \
    ((uint32_t)(offsetof(vinox_provenance_meta, kind) + sizeof(uint32_t)))

#ifdef __cplusplus
}
#endif

#endif
